# Generated by Django 3.1.3 on 2021-09-02 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocerybag', '0002_auto_20210902_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='status',
            field=models.CharField(choices=[('BOUGHT', 'BOUGHT'), ('NOT AVAILABLE', 'NOT AVAILABLE'), ('PENDING', 'PENDING')], max_length=40),
        ),
    ]
